### PR TITLE
updating all Gems

### PR DESCRIPTION
**Pull request by streeetlamp**
works on my machine lol

### CODE REVIEW

**Comment by streeetlamp** [comment]
works on my fork also 
https://streeetlamp.github.io/2019.code4lib.org/

**Comment by jcoyne** [comment]
It looks like you checked in `vendor/` do you want to do that?  This will make the repository very large.

**Comment by phette23** [comment]
The updated gems worked for me. But I agree that we shouldn't check in the vendor dir.

**Comment by streeetlamp** [comment]
thanks y'all, removed  

giphy-1

**Pull request merged**
